// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMeSgE-hFboTh36icF4wNMj39ILBMsZF4',
    appId: '1:1074601171821:web:196f7d9814ef8d142bd864',
    messagingSenderId: '1074601171821',
    projectId: 'newsapp-4008f',
    authDomain: 'newsapp-4008f.firebaseapp.com',
    storageBucket: 'newsapp-4008f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAadomsDfHzIdE_f3fhS2kcjP7EcGf2Ki4',
    appId: '1:1074601171821:android:a1904bffad03224e2bd864',
    messagingSenderId: '1074601171821',
    projectId: 'newsapp-4008f',
    storageBucket: 'newsapp-4008f.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJBQSAilyPlaK9fX7GDj1ZaUkKREzmmN0',
    appId: '1:1074601171821:ios:7512e986aaccd8af2bd864',
    messagingSenderId: '1074601171821',
    projectId: 'newsapp-4008f',
    storageBucket: 'newsapp-4008f.appspot.com',
    iosClientId: '1074601171821-ql4vj2q3f4dlltkosqivr6e10vgunn7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp2.RunnerTests',
  );
}
